version: '3.5'
services:
  basic-ui-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basic-ui-express
    ports:
      - ${PORT:-8080}:80
    logging:
      driver: json-file

  cmd-basic-ui-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmd-basic-ui-express
    command: "sleep infinity"
    ports:
      - ${PORT:-8080}:80
    volumes:
      - .:/app
    logging:
      driver: json-file